import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    
      <main className={styles.main}>
        <img src="/aragon.png" className={styles.logo} />
        <div className={styles.header}>
          <img src="/fight-for-freedom.svg" className={styles.fff} />
        </div>
        
        <iframe className={styles.iframe} src="https://linked.md/v?u=https://linked.md/api/github/luisivan/charter-ovote/main/Charter.linked.md"></iframe>
        <input type="checkbox" name="accept" value="true"/>
        <label for="accept">I have read and accept the terms outlined above by joining the Aragon DAO</label>
        <ConnectButton />
      </main>
    </div>
  );
};

export default Home;
